### ISSUE TITLE
Can't start tomcat

### ISSUE THREAD

**Issue by mrniko** [bmuschko/gradle-tomcat-plugin#115]
Here is my config:

apply plugin: 'com.github.ben-manes.versions'
apply plugin: 'com.bmuschko.tomcat'

buildscript {
   repositories {
      jcenter()
   }

   dependencies {
      classpath 'com.github.ben-manes:gradle-versions-plugin:0.6'
      classpath 'com.bmuschko:gradle-tomcat-plugin:2.0'
   }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'war'

sourceCompatibility = 1.8
version = 1.0

buildDir = 'target'

configurations.all {
   exclude group: 'commons-logging', module: 'commons-logging'
   exclude group: 'com.sun.xml.bind', module: 'jaxb-impl'
   exclude group: 'org.jboss.weld.se', module: 'weld-se'
}

ext {
   resteasyVersion = '3.0.10.Final'
   springSecurityVersion = '3.2.5.RELEASE'
   springVersion = '4.1.3.RELEASE'
   slf4jVersion = '1.7.9'
}

repositories {
   jcenter()
   mavenCentral()
   mavenLocal()
}

dependencies {

   testCompile 'junit:junit:4.11'

   compile "org.postgresql:postgresql:9.3-1102-jdbc41"

   compile "javax.ejb:javax.ejb-api:3.2",
           "javax.enterprise:cdi-api:1.0",
           "org.jboss.resteasy:resteasy-jackson2-provider:$resteasyVersion",
           "org.jboss.resteasy:resteasy-hibernatevalidator-provider:$resteasyVersion",
           "org.jboss.resteasy:resteasy-jaxrs:$resteasyVersion",
           "org.jboss.resteasy:resteasy-jaxb-provider:$resteasyVersion",
           "org.jboss.resteasy:resteasy-spring:$resteasyVersion"

   compile 'com.google.guava:guava:18.0'

   compile 'javax.servlet:javax.servlet-api:3.1.0'

   compile "org.springframework:spring-core:$springVersion",
           "org.springframework:spring-beans:$springVersion",
           "org.springframework:spring-context:$springVersion",
           "org.springframework:spring-orm:$springVersion",
           "org.springframework:spring-web:$springVersion"

   compile "org.springframework.security:spring-security-web:$springSecurityVersion",
           "org.springframework.security:spring-security-core:$springSecurityVersion",
           "org.springframework.security:spring-security-config:$springSecurityVersion"

   compile "org.slf4j:slf4j-api:$slf4jVersion",
           "org.slf4j:jcl-over-slf4j:$slf4jVersion"

   compile 'org.hibernate:hibernate-core:4.3.7.Final'
}

on `gradle tomcatRun` or `gradle tomcatRunWar` i have got:

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tomcatR
un'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
e(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
ter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.GradleException: An error occurred starting the Tomcat
 server.
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.startTomcat(Abstra
ctTomcatRun.groovy:371)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun$_validateConfigura
tionAndStartTomcat_closure2.doCall(AbstractTomcatRun.groovy:232)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun$_validateConfigura
tionAndStartTomcat_closure2.doCall(AbstractTomcatRun.groovy)
        at com.bmuschko.gradle.tomcat.internal.LoggingHandler.withJdkFileLogger(
LoggingHandler.groovy:56)
        at com.bmuschko.gradle.tomcat.internal.LoggingHandler$withJdkFileLogger.
callStatic(Unknown Source)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.validateConfigurat
ionAndStartTomcat(AbstractTomcatRun.groovy:231)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun$_start_closure1.do
Call(AbstractTomcatRun.groovy:224)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun$_start_closure1.do
Call(AbstractTomcatRun.groovy)
        at com.bmuschko.gradle.tomcat.internal.utils.TomcatThreadContextClassLoa
der.withClasspath(TomcatThreadContextClassLoader.groovy:31)
        at com.bmuschko.gradle.tomcat.internal.utils.ThreadContextClassLoader$wi
thClasspath.call(Unknown Source)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.start(AbstractTomc
atRun.groovy:223)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 44 more
Caused by: org.gradle.api.GradleException: Unable to resolve Tomcat server speci
fication version.
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory.readTomcatSpe
cVersionFromManifest(TomcatServerFactory.groovy:63)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory.this$2$readTo
mcatSpecVersionFromManifest(TomcatServerFactory.groovy)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory$this$2$readTo
mcatSpecVersionFromManifest$0.callCurrent(Unknown Source)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory.resolveTomcat
ServerImpl(TomcatServerFactory.groovy:41)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory.this$2$resolv
eTomcatServerImpl(TomcatServerFactory.groovy)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory$this$2$resolv
eTomcatServerImpl.callCurrent(Unknown Source)
        at com.bmuschko.gradle.tomcat.embedded.TomcatServerFactory.getTomcatServ
er(TomcatServerFactory.groovy:36)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.createServer(Abstr
actTomcatRun.groovy:389)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.startTomcat(Abstra
ctTomcatRun.groovy:323)
        ... 62 more

**Comment by kecsolecso** [comment]
Can you be more specific? Root cause, solution?
