### ISSUE TITLE
WebResourceSet creating exception

### ISSUE THREAD

**Issue by vrudas** [bmuschko/gradle-tomcat-plugin#116]
When I trying to run Gradle task tomcatRun I get this stacktrace:

```java
Caused by: java.lang.IllegalArgumentException: Unable to create WebResourceSet from [C:\Users\Vasiliy\OneDrive\Projects\IdeaProjects\testProject\web\build\classes\main]
	at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:416)
	at org.apache.catalina.webresources.StandardRoot.createWebResourceSet(StandardRoot.java:368)
	at org.apache.catalina.WebResourceRoot$createWebResourceSet.call(Unknown Source)
	at com.bmuschko.gradle.tomcat.embedded.Tomcat8xServer.addWebappResource(Tomcat8xServer.groovy:48)
	at com.bmuschko.gradle.tomcat.embedded.TomcatServer$addWebappResource$2.call(Unknown Source)
	at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.addWebappResource(AbstractTomcatRun.groovy:297)
	at com.bmuschko.gradle.tomcat.tasks.TomcatRun$_configureWebApplication_closure1.doCall(TomcatRun.groovy:151)
	at com.bmuschko.gradle.tomcat.tasks.TomcatRun.configureWebApplication(TomcatRun.groovy:150)
	at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.startTomcat(AbstractTomcatRun.groovy:327)
	... 88 more
```

my build file:

```groovy
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-tomcat-plugin:2.0'
    }
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'com.bmuschko.tomcat'

sourceCompatibility = 1.8
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    compile project(':core')

    providedCompile 'javax.servlet:javax.servlet-api:3.1.0'

    // tomcat 8
    def tomcatVersion = '8.0.17'
    tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
            "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}"
    tomcat("org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}") {
        exclude group: 'org.eclipse.jdt.core.compiler', module: 'ecj'
    }

    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```
when running task tomcatRunWar task run success, and also when I change version of Tomcat to 7.0.57.
Tried on Tomcat versions from 8.0.1 to 8.0.17 JDK 1.8.25

**Comment by bmuschko** [comment]
Tomcat 8.x is not officially supported. We have an initial implementation in place but to be honest it's not perfect. It would be great if we could make this more "production-ready". Would you be interested in looking into it?

What's the stack trace you see with Tomcat 7.x?

**Comment by tomwhoiscontrary** [comment]
I got this error too. It happened when my src/main/resources was empty. As soon as i put a file in it, the error went away.

I think the problem is that Gradle doesn't create build/resources/main unless it has something to put in it, but Tomcat requires that it exists even if it's empty. If you really don't have any resources, you could add:

```gradle
task createWebRoot << {
    sourceSets.main.output.resourcesDir.mkdirs()
}
tomcatRun.dependsOn createWebRoot
```
