### ISSUE TITLE
Unable to resolve Tomcat server specification version. 

### ISSUE THREAD

**Issue by attasiva** [bmuschko/gradle-tomcat-plugin#121]
Hi,

I am trying to start the embedded container and start some automation tests on it as part of same build. my build.gradle is as below:

buildscript {
	repositories {
		mavenCentral()
	}	
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:1.2.3.RELEASE")
		classpath 'com.bmuschko:gradle-tomcat-plugin:2.1'
	}
}

apply plugin: 'java'
apply plugin: 'spring-boot'

apply plugin: 'com.bmuschko.tomcat-base'

war {
	webXml = file('src/main/resources/web.xml')
	baseName = 'FileTransferProxy'
	version = '0.0.1-SNAPSHOT'
}

repositories {
	mavenCentral()
}

dependencies {
	def tomcatVersion = '7.0.52'
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile("org.springframework.boot:spring-boot-starter-test")
}

task itRun(type: com.bmuschko.gradle.tomcat.tasks.TomcatRun) {
	dependsOn(":build")
	daemon = true
}

i am getting below error when trying to run below command:

gradle clean itRun

Caused by: org.gradle.api.GradleException: Unable to resolve Tomcat server specification version.
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.readTomcatSpecVersionFromManifest(TomcatServerFactory.groovy:67)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.this$2$readTomcatSpecVersionFromManifest(TomcatServerFactory.groovy)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory$this$2$readTomcatSpecVersionFromManifest$0.callCurrent(Unknown Source)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.resolveTomcatServerImpl(TomcatServerFactory.groovy:41)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.this$2$resolveTomcatServerImpl(TomcatServerFactory.groovy)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory$this$2$resolveTomcatServerImpl.callCurrent(Unknown Source)
	at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.getTomcatServer(TomcatServerFactory.groovy:37)
	at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.createServer(AbstractTomcatRun.groovy:383)
	at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.startTomcat(AbstractTomcatRun.groovy:317)

how can I resolve this issue?

**Comment by bmuschko** [comment]
You are not assign the Tomcat libraries to the `tomcat` configuration. See [documentation](https://github.com/bmuschko/gradle-tomcat-plugin#assigning-the-tomcat-libraries) for more info.
