### ISSUE TITLE
Unable to resolve Tomcat server specification version

### ISSUE THREAD

**Issue by rumatoest** [bmuschko/gradle-tomcat-plugin#128]
This error occurs in plugin version since 2.1
My tomcat is 
~~~
def tomcatVersion = '7.0.59'
classpath "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"
classpath "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}"
classpath "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"
classpath "org.apache.tomcat:tomcat-servlet-api:${tomcatVersion}"
classpath "org.apache.tomcat:tomcat-jsp-api:${tomcatVersion}"
~~~
On plugin version 2.0 and previous is works

```
Caused by: org.gradle.api.GradleException: Unable to resolve Tomcat server specification version.
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.readTomcatSpecVersionFromManifest(TomcatServerFactory.groovy:67)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.this$2$readTomcatSpecVersionFromManifest(TomcatServerFactory.groovy)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory$this$2$readTomcatSpecVersionFromManifest$0.callCurrent(Unknown Source)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.resolveTomcatServerImpl(TomcatServerFactory.groovy:41)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.this$2$resolveTomcatServerImpl(TomcatServerFactory.groovy)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory$this$2$resolveTomcatServerImpl.callCurrent(Unknown Source)
        at com.bmuschko.gradle.tomcat.embedded.factory.TomcatServerFactory.getTomcatServer(TomcatServerFactory.groovy:37)
        at com.bmuschko.gradle.tomcat.tasks.AbstractTomcatRun.startTomcat(AbstractTomcatRun.groovy:323)
        ... 87 more

```

**Comment by bmuschko** [comment]
You are using the wrong configuration. It should be `tomcat` and not `classpath`. See README for more information.

**Comment by djmdevs** [comment]
Tks bm, it solves for me
