### ISSUE TITLE
JasperInitializer in tomcat 8 embedded mode

### ISSUE THREAD

**Issue by mkornipati** [bmuschko/gradle-tomcat-plugin#132]
Hi, We are in the process of migrating embedded tomcat application from 7.0.59 to tomcat 8.0.x After updating the Tomcat version and plugin version to 2.2.2, and then  "tomcatRun". When trying to access the home page I'm getting a NullPOinterException

```
java.lang.NullPointerException: null
        at org.apache.jasper.JspCompilationContext.getTldResourcePath(JspCompilationContext.java:551) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:415) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:474) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1430) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Parser.parse(Parser.java:139) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.ParserController.parse(ParserController.java:100) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323) ~[tomcat-embed-jasper-8.0.27.jar:8.0.27]
```
and after my investigation. found that tldCache inside the EmbeddedServletOption is null. Which seems to be set by the onStartup method in the JasperInitializer.

So, to resolve this by fixing the [code](https://github.com/bmuschko/gradle-tomcat-plugin/commit/6c9b5270cf6a3689d7cd86cebe9f0ad451b5f7e6) - https://github.com/bmuschko/gradle-tomcat-plugin/commit/6c9b5270cf6a3689d7cd86cebe9f0ad451b5f7e6

Can you please review this and confirm. If you are OK,  I can create a pull request with this fix.

**Comment by bmuschko** [comment]
Did you try this out for your sample project? If yes, you can open a pull request.

**Comment by mkornipati** [comment]
Yes @bmuschko. Sure, will open a pull request some time today. Thanks.
