### ISSUE TITLE
ClassCastException: Cannot cast [...]JerseyServletContainerInitializer to [...]ServletContainerInitializer

### ISSUE THREAD

**Issue by liratanak** [bmuschko/gradle-tomcat-plugin#138]
I am not sure what happen to my existing project from Eclipse.
I'm tried to move to gradle, but I faced below problem.
( I did tried with `jetty` it worked, but no luck with `tomcat`(7.0.59) )

Really appreciate for suggestion. Thanks in advanced

```
Failed to process JAR found at URL [/MyProject] for ServletContainerInitializers for context with name [{1}]
java.io.IOException: java.lang.ClassCastException: Cannot cast com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer to javax.servlet.ServletContainerInitializer
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:196)
	at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:152)
	at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1577)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1281)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:889)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:386)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5412)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: Cannot cast com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer to javax.servlet.ServletContainerInitializer
	at java.lang.Class.cast(Class.java:3186)
	at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:188)
	... 15 more
Marking this application unavailable due to previous error(s)
Error getConfigured
Context [/MyProject] startup failed due to previous errors
Started Tomcat Server
The Server is running at http://localhost:9090/MyProject
> Building 90% > :tomcatRun
```

**Comment by bmuschko** [comment]
The issue you are seeing is likely what's described under "Why do I get a java.lang.ClassCastException on javax.servlet.Servlet" in the FAQ of the README.md file. Please refer to the solution there and close the issue if that fixes it for you.

**Comment by liratanak** [comment]
Thanks @bmuschko for remining
At that time I did read the "FAQ" but maybe something else problems ( just getting started learning gradle )

and I was confusing on `servlet-api` which I am using `javax.servlet:javax.servlet-api:3.0.1` and I put ( from the FAQ )
```
providedCompile 'javax.servlet:servlet-api:2.5',
                'javax.servlet:jsp-api:2.0'
```
I got above error, then just update to:
```
providedCompile 'javax.servlet:javax.servlet-api:3.0.1',
                'javax.servlet:jsp-api:2.0'
```

It's fixed for me.
Thanks again

Sincerely,
Liratanak

**Comment by hongqijia** [comment]
I followed the suggestions above, but I ended with the following error:
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/catalina/loader/WebappClassLoader) previously initiated loading for a different type with name "javax/servlet/ServletContext"
I tried some other options that suggested by other people on the Internet, but those all lead to a switch between the java.lang.LinkageError and the java.lang.ClassCastException.

Thanks for any suggestions, I'm quite desperate here.

Regards,
Hong
