### ISSUE TITLE
Plugin version 2.4 throws NoClassDefFoundError for Jasper task

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-tomcat-plugin#162]
Version 2.4 of the plugin does not find the class `org/apache/jasper/TrimSpacesOption`.

```
plugins {
    id "com.bmuschko.tomcat" version "2.4"
}
```

```
Caused by: java.lang.NoClassDefFoundError: org/apache/jasper/TrimSpacesOption
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:72)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:283)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:238)
        at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:110)
        ... 121 more
Caused by: java.lang.ClassNotFoundException: org.apache.jasper.TrimSpacesOption
        ... 127 more
```

**Comment by bmuschko** [comment]
@kasecato Looks like there's an issue with the changes you provided in the pull request https://github.com/bmuschko/gradle-tomcat-plugin/pull/160. Would you mind looking into it? We'll likely need to look up the class via reflection and set it to null if it can't be found on the classpath.
