### ISSUE TITLE
Gradle Daemon - Caused by: java.lang.Error: factory already defined

### ISSUE THREAD

**Issue by sgoldstein527** [bmuschko/gradle-tomcat-plugin#187]
When using the Gradle daemon (the default), I'm unable to run Tomcat twice using the plugin.  The first time it starts, there is no problem.  I then run "gradle tomcatStop" followed by "gradle tomcatRun" to restart Tomcat.  I get the error/stacktrace below.  If I run, "gradle --stop" to stop the gradle daemon, I'm once again able to run "gradle tomcatRun" successfully.

I'm using the plugin version 2.5 and Tomcat version 9.0.22.  

Caused by: java.lang.Error: factory already defined
        at java.base/java.net.URL.setURLStreamHandlerFactory(URL.java:1184)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77)
        at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:701)
        at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:683)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        ... 175 more

**Comment by C-Otto** [comment]
Workaround: `./gradlew tomcatRun --no-daemon`

**Comment by danieljeremias** [comment]
Is threre a real solution for this case?
